### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by Jack5079** [mollersuite/mollermethod#66]
### Pros
- It's a positive attribute
### Cons
- v5.0.0 was codenamed trendsetter, v10 is codenamed trendsetter2, meaning its confusing as hell
### Pros
- Named after an animal sorta like "moller"
- Not gonna be taken
- [Logo is obvious](https://github.com/catppuccin/wallpapers/blob/main/minimalistic/dark-cat.png)
### Cons
- Used in various (unreleased) experiments
- Proposed logo doesn't work at small sizes

**Comment by Jack5079** [comment]
Catay logo
![catay](https://user-images.githubusercontent.com/29169102/185770973-9fda95ba-dc12-4ed7-ad0b-441fe21eb3b7.svg)

**Comment by Jack5079** [comment]
Rebrand Luau.ml to fecode, because fe = filtering enabled and first two letters of feline is also fe
![fecode](https://cdn.discordapp.com/attachments/1001361710319411220/1010981296106913832/catay-script.png)

**Comment by Jack5079** [comment]
We need a tagline

**Comment by Jack5079** [comment]
nvm mollermethod is a way better name

**Comment by worstending** [comment]
> nvm mollermethod is a way better name

jack after lying

**Comment by Jack5079** [comment]
fuck you
