### ISSUE TITLE
Paragrah BUG

### ISSUE THREAD

**Issue by andrew351** [mollersuite/mollermethod#72]
let's say i create a paragraph with following code
 `Tab:AddParagraph("Title", "Description")`
and now if i do 
`Tab:Set("New Title", "New Description")`
it will actually set the paragraph description to "New Title", and doesn't even change the description, and the title will still be "Title"

**Comment by maumaumaumaumaumau** [comment]
The issue was closed, was this problem fixed?

**Comment by Jack5079** [comment]
This is the mollermethod/Catay issue tracker. If this is a Orion bug, ask Sirius support.
