### ISSUE TITLE
Among Us

### ISSUE THREAD

**Issue by Toon-arch** [mollersuite/mollermethod#79]
coping rn

**Comment by Jack5079** [comment]
Your feature suggestion will be evaluated and implemented by a developer soon.

**Comment by Jack5079** [comment]
Windows is unbearably slow but I'll try to get this done anyway

**Comment by Jack5079** [comment]
Implemented! 
https://user-images.githubusercontent.com/29169102/190927015-cb5b0558-03aa-4816-8ef4-5d6a820d5a8e.mp4

**Comment by Jack5079** [comment]
done

**Comment by Toon-arch** [comment]
wtf
based gigachad
